apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp-deployment
    tier: frontend
spec:
  replicas: 3
  template:
    metadata:
      name: myapp-deployment
      labels:
        app: myapp-deployment
        tier: frontend
    spec:
      containers:
        - name: myapp-deployment
          image: nginx
  selector:
    matchLabels:
       app: myapp-deployment